### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by harston** [hirorinao/atom-editing-diff#1]
1. Run atom with previosly opened documents

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [editing-diff](https://github.com/hirorinao/atom-editing-diff) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /Users/admin/.atom/packages/editing-diff/node_modules/diff/lib/diff/line.js:20

TypeError: Cannot read property 'split' of null
    at Object.lineDiff.tokenize (/Users/admin/.atom/packages/editing-diff/node_modules/diff/lib/diff/line.js:20:31)
    at Object.diff (/Users/admin/.atom/packages/editing-diff/node_modules/diff/lib/diff/base.js:36:39)
    at Object.diffLines (/Users/admin/.atom/packages/editing-diff/node_modules/diff/lib/diff/line.js:45:19)
    at RepositoryFile.module.exports.RepositoryFile.getLineDiffs (/Users/admin/.atom/packages/editing-diff/lib/repository-file.coffee:15:20)
    at EditingDiffView.module.exports.EditingDiffView.updateDiffs (/Users/admin/.atom/packages/editing-diff/lib/editing-diff-view.coffee:102:32)
    at Immediate._onImmediate (/Users/admin/.atom/packages/editing-diff/lib/editing-diff-view.coffee:1:1)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```
### Commands

```
     -0:01.1.0 application:new-file (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "line-diff-details"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
editing-diff, v0.2.0
language-lua, v0.9.4
minimap, v4.19.0
seti-icons, v0.4.5
seti-syntax, v0.4.1
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by hiro-ao** [comment]
fixed @f8a125403bc9f2f7bd6d32524d228f99b38bee16
